@startuml headers 

object main{
    主函数
}
object Application{
    应用层
}
object CubeCraft{
    CubeCraft
}
object Context{
    上下文
}

object Camera{
    摄像机
}
object Shader{
    着色器加载
}

object Log{
    日志输出
}
object Config{
    相关配置
}

object glm{
    线性代数库
}
object GLFW_GLAD{
    你懂的
}

object Texture{
    加载纹理
}

object Renderer{
    渲染相关
}
object Chunk{
    区块
}

Application --> main
CubeCraft --> Application

Camera --> CubeCraft
glm --> CubeCraft
Config -> CubeCraft
Texture --> CubeCraft
Renderer -left-> CubeCraft

GLFW_GLAD --> Context
Shader --> Context
Log -left-> Context
CubeCraft --> Context

GLFW_GLAD --> Texture
Log --> Texture

@enduml