@startuml headers 

object main{
    主函数
}

package Enviroment{
    object glm{
        线性代数库
    }
    object GLFW_GLAD{
        你懂的
    }
    'glm -right-> GLFW_GLAD
}

package Scr{
    package Log{
        object Log{
            日志输出
        }
    }
    package Maths{
        object Croods{
            坐标相关
        }
    }
    package Renderer{
        object Renderer{
            渲染相关
        }
    }
    package Texture{
        object Texture{
            加载纹理
        }
    }
    package World{
        package Chunk{
            object Chunk{
                区块
            }
            object ChunkMeshBuilder{
                构建区块Mesh
            }
            object Mesh{
                Mesh对象
            }
            object VerticesData{
                构建Mesh时的必要数据
            }
        }
    }
    object Application{
        应用层
    }
    object CubeCraft{
        CubeCraft
    }
    object Context{
        上下文
    }
    object Camera{
        摄像机
    }
    object Shader{
        着色器加载
    }
    object Config{
        相关配置
    }
}

Maths -[hidden]- Log
Log -[hidden]left- Texture

Application --> main
CubeCraft --> Application

Camera --> CubeCraft
Config --> CubeCraft
Texture --> CubeCraft
Renderer --> CubeCraft
Chunk -->CubeCraft

Shader --> Context
Log --> Context
CubeCraft --> Context

Log --> Texture

Mesh --> Chunk
ChunkMeshBuilder --> Chunk

Croods -right-> ChunkMeshBuilder
VerticesData --> ChunkMeshBuilder

@enduml